apiVersion: v1
kind: Service
metadata:
  name: labfinal-services
  labels:
    name: labfinal-services
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    name: labfinal-services